---
- name: Setup GCP Access on WSL Ubuntu
  hosts: localhost
  become: true
  tasks:
    - name: Add Google Cloud CLI GPG key
      ansible.builtin.shell:
        cmd: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      args:
        executable: /bin/bash

    - name: Add Google Cloud CLI repository
      ansible.builtin.shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      args:
        executable: /bin/bash

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Google Cloud CLI
      apt:
        name: google-cloud-cli
        state: present

    - name: Install GKE Auth Plugin
      apt:
        name: google-cloud-sdk-gke-gcloud-auth-plugin
        state: present

    - name: Set environment variable for GKE Auth Plugin (for current user)
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export USE_GKE_GCLOUD_AUTH_PLUGIN=True'
        state: present
      become: false  # Make sure this runs as the current user

    - name: Source the updated .bashrc
      ansible.builtin.shell:
        cmd: source ~/.bashrc
      args:
        executable: /bin/bash
      become: false  # Run as the current user