---
- name: Install HashiCorp Vault on Ubuntu (including WSL)
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure necessary dependencies are installed
      apt:
        name: 
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Download HashiCorp Vault binary
      get_url:
        url: "https://releases.hashicorp.com/vault/1.14.2/vault_1.14.2_linux_amd64.zip"
        dest: /tmp/vault.zip
        mode: '0644'

    - name: Unzip Vault binary
      unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Set executable permissions for Vault binary
      file:
        path: /usr/local/bin/vault
        mode: '0755'

    - name: Verify Vault installation
      command: vault --version
      register: vault_version

    - name: Display Vault version
      debug:
        msg: "Installed Vault version: {{ vault_version.stdout }}"

    - name: Set up Vault autocomplete
      command: vault -autocomplete-install
      environment:
        SHELL: /bin/bash

    - name: Configure Vault as a systemd service (optional)
      copy:
        dest: /etc/systemd/system/vault.service
        content: |
          [Unit]
          Description=HashiCorp Vault - A tool for managing secrets
          Documentation=https://www.vaultproject.io/docs/
          After=network-online.target
          Wants=network-online.target

          [Service]
          ExecStart=/usr/local/bin/vault server -dev
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start Vault Service

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start Vault Service
      service:
        name: vault
        state: started
        enabled: yes
